public enum ListenType
{
    DEFAULT = 0,
    UPDATE_STATE_CALCULATOR,
    INIT_CALCULATOR,
    SEND_HEAL_VALUE,
    PLAYER_SEND_HEAL_VALUE,
    CREEP_SEND_HEAL_VALUE,
    CREEP_UPDATE_HEAL_VALUE,
    CREEP_IS_DEAD,
    BOSS_SEND_HEAL_VALUE,
    BOSS_UPDATE_HEAL_VALUE,
    BOSS_STATE_CURRENT,
    BOSS_SENDER_DAMAGED,
    PLAYER_PRESS_BUTTON_J,
    PLAYER_IS_COLLISION,
    PLAYER_IS_TALKING_NPC,
    PLAYER_HAS_ACCEPT_QUEST,
    PLAYER_SEND_DAMAGE_VALUE,
    PLAYER_SEND_POINT,
    PLAYER_PRESS_LEFT_SHIFT,
    PLAYER_PRESS_V_DODGE,
    PLAYER_SEND_STAMINA_VALUE,
    PLAYER_UPDATE_STAMINA_VALUE,
    PLAYER_FULL_STAMINA,
    PLAYER_REGEN_STAMINA,
    PLAYER_STAMINA_EMPTY,
    PLAYER_MANA_EMPTY,
    PLAYER_SEND_MANA_VALUE,
    PLAYER_UPDATE_MANA_VALUE,
    PLAYER_SKILL_CONSUMPTION_MANA,
    PLAYER_MOVE_STAMINA_CONSUMPTION,
    PLAYER_DODGE_STAMINA_CONSUMPTION,
    PLAYER_MOVE_STOP,
    PLAYER_DODGE_STOP,
    PLAYER_SKILL_KEYDOWN,
    UI_POPUP_SCROLLMAGIC_CLICK_EXIT_BTN,
    UI_SEND_LIST_ITEM_REWARD,
    ITEM_USE_DATA_IS_HEAL,
    ITEM_USE_DATA_IS_MANA,
    UI_SEND_SCREEN_SLIDER_EXP,
    UI_SEND_VALUE_EXP_TO_SLIDER,
    UI_SEND_CANVASMAIN,
    UI_SEND_VALUE_LEVEL,
    UI_UPDATE_ITEM_MISSION,
    UI_SEND_BUTTON_PRESS_AND_TYPESKILL,
    CAMERA_SEND_VALUE,
    MENU_BTN_START_CLICK,
    SE_ICONSCROLLMAGIC_ONCLICK,
    UI_SEND_POS_SLIDER_EXP,
    QUEST_COMPLETE,
    UPDATE_COUNT_ITEM,
    PU_BOXSKILL_SEND_TEXT,
    


}

public enum CalculatorButtonState
{
    DEFAULT = 0,
    NUMERIC,
    LATIN
}
public enum UIType
{
    Unknow = 0,
    Screen = 1,
    Popup = 2,
    Notify = 3
}
public enum CreepType
{
    unknow = 0,
    BAT,
    DRAGON,
    WORM,
}

