public enum ListenType
{
    DEFAULT = 0,
    UPDATE_STATE_CALCULATOR,
    INIT_CALCULATOR,
    SEND_HEAL_VALUE,
    PLAYER_SEND_HEAL_VALUE,
    CREEP_SEND_HEAL_VALUE,
    CREEP_UPDATE_HEAL_VALUE,
    BOSS_SEND_HEAL_VALUE,
    BOSS_UPDATE_HEAL_VALUE,
    BOSS_STATE_CURRENT,
    BOSS_SENDER_DAMAGED,
    PLAYER_PRESS_BUTTON_J,
    PLAYER_IS_COLLISION,
    PLAYER_IS_TALKING_NPC,
    PLAYER_HAS_ACCEPT_QUEST,
    PLAYER_SEND_DAMAGE_VALUE,
    PLAYER_SEND_POINT,
    UI_POPUP_SCROLLMAGIC_CLICK_EXIT_BTN,
    UI_SEND_LIST_ITEM_REWARD,
    ITEM_USE_DATA_IS_HEAL,
    UI_SEND_SCREEN_SLIDER_EXP,
    UI_SEND_VALUE_EXP_TO_SLIDER,
    UI_SEND_CANVASMAIN,
    UI_SEND_VALUE_LEVEL,
    
}

public enum CalculatorButtonState
{
    DEFAULT = 0,
    NUMERIC,
    LATIN
}
public enum UIType
{
    Unknow = 0,
    Screen = 1,
    Popup = 2,
    Notify = 3
}

